# Reference: https://github.com/codecov/support/wiki/Codecov-Yaml

coverage:
  ignore:
    - "tests"
    - "dart/external"
    - "dart/gui"
    - "extras/dartc"

comment:
  layout: "diff, flags, files"
