# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: CI macOS

on:
  push:
    branches:
      - "**"
  schedule:
    # Run at 09:00 UTC (02:00 PDT) every other day
    - cron: "0 9 * * 0/2"

jobs:
  # macOS 10.15 (Catalina)
  catalina_clang_release:
    name: ${{ matrix.build_type }}
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
    env:
      COMPILER: clang
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_DARTPY: "${{ matrix.build_type == 'Debug' && 'OFF' || 'ON' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: .ci/install_osx.sh
      - name: Build
        run: sudo -E .ci/build.sh
