name: CI macOS

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    # Cron sytax: [minute hour day_of_the_month month day_of_the_week]
    - cron: "0 2 * * 0,3" # Run every Sunday and Wednesday at 02:00

jobs:
  macos_clang_release:
    name: macOS
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang]
        build_type: [Debug, Release]
    env:
      COMPILER: ${{ matrix.compiler }}
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_TESTS: ON
      BUILD_BENCHMARKS: "${{ matrix.build_type == 'Release' && 'ON' || 'OFF' }}"
      BUILD_PYTHON_BINDING: ON
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: ./.ci/install_deps_osx.sh
      - name: Build
        run: sudo -E ./.ci/build.sh
