name: Docker Image

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    # Cron syntax: [minute hour day_of_the_month month day_of_the_week]
    - cron: "0 2 * * 0,3" # Run every Sunday and Wednesday at 02:00

env:
  DOCKER_REPO: dartsim/dart # https://hub.docker.com/repository/docker/dartsim/dart

jobs:
  # Ubuntu distros (bionic, focal, groovy, hirsute) on multiple architectures (amd64, arm64, ppc64le, s390x)
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [focal]
    env:
      UBUNTU_VERSION: ${{ matrix.distro }}
      DART_VERSION: v8.0
    steps:
      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile.ubuntu.${{ env.UBUNTU_VERSION }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ env.DOCKER_REPO }}:ubuntu-${{ env.UBUNTU_VERSION }}-${{ env.DART_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
